---
- hosts: 127.0.0.1
  become: true
  tasks:
  - name: Wait until the file /root/.kube/config is present before continuing
    wait_for:
      path: /root/.kube/config

  - shell: 'ip addr show ens4 | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*"'
    register: cloud_ip

  - name: Untaint the master in order to be able to run the cloudcore
    command: kubectl taint nodes node-role.kubernetes.io/master- --all

  - name: Download metrics-server manifest to the cluster.
    ansible.builtin.get_url:
      url: https://docs.projectcalico.org/manifests/calico.yaml
      dest: ~/calico.yaml
      mode: '0664'

  - name: Apply metrics-server manifest to the cluster.
    command: kubectl apply -f ~/calico.yaml

  ######################################### KUBEEDGE ###################################
  - name: Unarchive keadm
    ansible.builtin.unarchive:
      src: https://github.com/kubeedge/kubeedge/releases/download/v1.8.2/keadm-v1.8.2-linux-amd64.tar.gz
      dest: "/root/"
      remote_src: yes

  - name: Make keadm executable
    file: 
      dest: /root/keadm-v1.8.2-linux-amd64/keadm/keadm
      mode: u+x

  - name: Execute keadm
    command: |
      /root/keadm-v1.8.2-linux-amd64/keadm/keadm init --kubeedge-version=1.8.2 --advertise-address={{ cloud_ip.stdout }} --kube-config=/root/.kube/config
      
  ########################################### LOGGING  #####################################
  - name: Get certgen and fix permissions
    get_url:
      url: https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/tools/certgen.sh
      dest: "/root/"
      mode: '0755'

  - name: Get certgen and fix permissions
    get_url:
      url: https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.5.2/components.yaml
      dest: "/root/deploy.yaml"
      mode: '0755'

  - name: Move certgen to KubeEdge directory
    command: mv "/root/certgen.sh" /etc/kubeedge/

  - name: Execute certgen
    shell: CLOUDCOREIPS="{{ cloud_ip.stdout }}" /etc/kubeedge/certgen.sh stream
  
  - name: Add ip to ip table
    command: iptables -t nat -A OUTPUT -p tcp --dport 10351 -j DNAT --to {{ cloud_ip.stdout }}:10003

  - name: Enable cloudstream
    shell: "sed -z 's/enable: false/enable: true/2' /etc/kubeedge/config/cloudcore.yaml > /root/cloudcore.yaml" 
    args:
      warn: false

  - name: Move the newly created cloudcore to KubeEdge directory
    command: mv -f "/root/cloudcore.yaml" /etc/kubeedge/config/cloudcore.yaml

  - name: Kill cloudcore
    command: pkill cloudcore

  - name: Restart cloudcore
    command: sudo su -c 'nohup cloudcore > cloudcore.log 2>&1 &'
    args:
      warn: false

  - name: Copy metrics yaml to local directory from remote"
    copy:
      src: "/opt/ansible/manifests/metrics.yaml"
      dest: "/root/metrics.yaml"
      remote_src: true

  - name: Add metrics server
    command: kubectl apply -f /root/metrics.yaml

  ################################### TOKEN #####################################
  - name: Get join token console
    command: |
      /root/keadm-v1.8.2-linux-amd64/keadm/keadm gettoken
    register: token_command
      
  - local_action:
      module: copy
      content: "keadm join --cloudcore-ipport={{ cloud_ip.stdout }}:10000 --token={{ token_command.stdout }} --kubeedge-version=1.8.0"
      dest: "/root/join-command.txt"

  - name: Copy join command to google cloud bucket
    command: "gsutil cp /root/join-command.txt {{ bucket_url }}"
