apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-classification-deployment
  labels:
    app: image-classification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classification
  template:
    metadata:
      labels:
        app: image-classification
    spec:
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubeedge.io
        value: edge
      containers:
      - name: image-classification
        image: redplanet00/kubeedge-applications:image_classification_combined
        ports:
        - containerPort: 1883

