---
- hosts: cloudcore
  vars:
      cloud_ip: 192.168.56.2
  tasks:
  - user:
      name: "{{username}}"
      state: present
    register: registered_user

  # Initialize the kubernetes cluster.
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --kubernetes-version=1.21.0 --apiserver-advertise-address={{ cloud_ip }} --apiserver-cert-extra-sans={{ cloud_ip }}
    become: true

  - file:
      path: /etc/kubernetes/admin.conf
      mode: o+r
    become: true

  - name: Ensures {{registered_user}}/.kube
    file: 
      path: "{{registered_user.home}}/.kube"
      state: directory

  - name: Copy file
    copy:
      src: /etc/kubernetes/admin.conf 
      dest: "{{registered_user.home}}/.kube/config"
    become: true
    become_user: "{{username}}"

  - name: Ensures /root/.kube
    file: 
      path: "/root/.kube"
      state: directory
    become: true

  - name: Copy kubeconfig to "/root/.kube/config"
    copy:
      src: /etc/kubernetes/admin.conf 
      dest: "/root/.kube/config"
    become: true

  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: "{{registered_user.home}}/.kube/config"
      owner: "{{registered_user.uid}}"
      group: "{{registered_user.group}}"
    become: true
    become_user: "{{username}}"

  - name: Untaint the master in order to be able to run the cloudcore
    command: kubectl taint nodes node-role.kubernetes.io/master- --all
    become: true
    become_user: "{{username}}"

  - name: Install Calico
    command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    become: true
    become_user: "{{username}}"

  # Download and unpack keadm for cloudcore installation.
  - name: Unarchive keadm
    ansible.builtin.unarchive:
      src: https://github.com/kubeedge/kubeedge/releases/download/v1.8.2/keadm-v1.8.2-linux-amd64.tar.gz
      dest: "/{{registered_user.home}}/"
      remote_src: yes

  - name: Make keadm executable
    file: 
      dest: /{{registered_user.home}}/keadm-v1.8.2-linux-amd64/keadm/keadm
      mode: u+x
    become: true

  - name: Execute keadm
    command: |
      {{registered_user.home}}/keadm-v1.8.2-linux-amd64/keadm/keadm init --kubeedge-version=1.8.2 --advertise-address={{ cloud_ip }} --kube-config=/{{registered_user.home}}/.kube/config
    become: true
