---
- hosts: all:!cloudcore
  tasks:
  - command: whoami
    register: username

  - user:
      name: "{{username.stdout}}"
      state: present
    register: registered_user

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - conntrack
      - docker.io
    become: true

  - name: Ensure docker service is running
    systemd:
      name: docker
      state: started
    become: true

  - name: Add edge user to docker group
    user:
      name: "{{ username.stdout }}"
      groups: "docker, systemd-journal"
    become: true
    
  - name: Restart docker service
    command: systemctl restart docker
    become: true

  - name: Reload ip settings
    command: sysctl -p
    become: true

  - name: Reload ip settings
    command: sysctl -p
    become: true

  - name: Get KubeEdge and unarchive it
    unarchive:
      src: https://github.com/kubeedge/kubeedge/releases/download/v1.8.0/keadm-v1.8.0-linux-amd64.tar.gz
      dest: "/{{registered_user.home}}"
      remote_src: true
    become: true

  - name: Make KubeEdge executable
    file:
      dest: "/{{registered_user.home}}/keadm-v1.8.0-linux-amd64/keadm/keadm"
      mode: +x
    become: true

  - name: Move KubeEdge executable
    command: mv "/{{registered_user.home}}/keadm-v1.8.0-linux-amd64/keadm/keadm" /usr/local/bin
    become: true

  - name: Remove unneeded KubeEdge files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/{{registered_user.home}}/keadm-v1.8.0-linux-amd64"
      - "/{{registered_user.home}}/keadm-v1.8.0-linux-amd64.tar.gz"
    become: true

  - name: Wait for join command to be finished on cloud controller
    wait_for:
      path: /{{registered_user.home}}/manifests/edgecore/join-command.txt
      state: present
    become: false

  - name: Copy the join command to the edge node
    copy: 
      src: /{{registered_user.home}}/manifests/edgecore/join-command.txt 
      dest: /{{registered_user.home}}/join-command.txt
      remote_src: true
    become: true

  - name: Join the cloud controller kubernetes server
    shell: "$(cat join-command.txt)"
    become: true

  ####################### LOGGING #################################

  - name: Enable edgestream
    shell: "sed -z 's/enable: false/enable: true/3' /etc/kubeedge/config/edgecore.yaml > edgecore.yaml" 
    args:
      warn: false
    become: true

  - name: Move the newly created edgecore to KubeEdge directory
    command: mv -f "/{{registered_user.home}}/edgecore.yaml" /etc/kubeedge/config/edgecore.yaml
    become: true

  - name: Disable KubeProxy restart
    shell: "sed '/^ExecStart=.*/a Environment=\"CHECK_EDGECORE_ENVIRONMENT=false\"' /etc/kubeedge/edgecore.service > edgecore.service" 
    args:
      warn: false
    become: true

  - name: Move the newly created edgecore service to KubeEdge directory
    command: mv -f "/{{registered_user.home}}/edgecore.service" /etc/kubeedge/edgecore.service
    become: true

  - name: Kill kube-proxy
    shell: pkill kube-proxy || true
    become: true

  - name: Restart edgecore
    command: systemctl restart edgecore.service
    become: true

  handlers:
    - name: docker status
      service:
        name: docker
        state: started