---
- hosts: cloudcore
  tasks:
  - user:
      name: "{{username}}"
      state: present
    register: registered_user

  - name: Get join token console
    command: |
      {{registered_user.home}}/keadm-v1.8.2-linux-amd64/keadm/keadm gettoken
    register: token_command
    become: true

  - debug:
      var: token_command
      verbosity: 2

  - local_action:
      module: copy
      content: "{{ token_command.stdout }}"
      dest: "/{{registered_user.home}}/join-token.txt"

  - name: Wait
    command: sleep 10

  - name: Copy join token to shared folder
    copy:
      src: "/{{registered_user.home}}/join-token.txt"
      dest: "/{{registered_user.home}}/manifests/edgecore/join-token.txt"
      remote_src: true
    become: true
